### ISSUE TITLE
Application crashes on Windows.

### ISSUE THREAD

**Issue by Dantoys** [EndlessSkyCommunity/ESLauncher2#415]
Hello, Thanks to all that keeps this project/game going. I do enjoy :)

I downloaded the latest version of ESLauncher, and the application crashes, I am attaching the Log for you troubleshooting. I am running an older version till this issue gets fixed or a new version comes out. Have a Blessed day!
[Report.wer..txt](https://github.com/EndlessSkyCommunity/ESLauncher2/files/14967740/Report.wer.txt)

**Comment by MCOfficer** [comment]
I'll be honest, i've never seen that type of log before and it doesn't really tell me anything. Can you try to run the executable from the terminal and see what you get?

Another thing to try: we recently had some large dependency upgrades, can you reproduce it with 0.8.12?

**Comment by Inglonias** [comment]
I'm also having this error. I'll try to run the app from the terminal, see what appears

**Comment by Inglonias** [comment]
Here's my ES2 log file
[ESLauncher2.log](https://github.com/EndlessSkyCommunity/ESLauncher2/files/15140308/ESLauncher2.log)

**Comment by Inglonias** [comment]
0.9.3 works, 0.9.4 does not

**Comment by MCOfficer** [comment]
Thanks, that does give me an idea. There's no error message, but it's curious that wgpu is still in the logs, which indicates hardware rendering. That's also the only change made in 0.9.4 that I reckon could cause a full crash (enabling the `web-colors` features, which changes the way some things are rendered).

Either way, wgpu should've been removed a while ago; I double-checked, and it turns out some dependency was still pulling it in. Please try again with 0.9.5 which uses good ol' software rendering.

**Comment by Inglonias** [comment]
0.9.5 is functional. Good work.
